### ISSUE TITLE
Webpack beta 25 breaks everything..

### ISSUE THREAD

**Issue by mikecann** [danielearwicker/immuto#9]
Hi,

Just following your excellent guide (https://danielearwicker.github.io/immuto/getting_started/creating_the_project.html), problem is when you do so it installes webpack beta25 which is apparently broken (https://github.com/webpack/webpack/issues/3018), you have to manually install beta 22.. thought you would want a heads up on that.

Mike

**Comment by danielearwicker** [comment]
Strange, when I remove webpack and `npm -g install webpack` I get 1.13.2. How did you get a beta version of a 2.x?

**Comment by eshimischi** [comment]
@danielearwicker 

package.json:
...
 "webpack": "2.1.0-beta.22"
...

**Comment by mikecann** [comment]
@danielearwicker I have no idea, I just followed the instructions... Ah.. perhaps I had a beta version of it installed globally already so doing `npm -g install webpack` updated to the latest beta?

**Comment by danielearwicker** [comment]
@mikecann I think that's probably it. Suggest `npm -g remove webpack` and retry!

@eshimischi - which file are you seeing that in? In `immuto`, `immuto-react` and `immuto-example`, it's required like this:

```
"webpack": "^1.13.2"
```

**Comment by eshimischi** [comment]
@danielearwicker nope i meant that @mikecann changed the package.json into webpack2 instead of v1 and got a troubles with your project!

**Comment by danielearwicker** [comment]
Ok thanks, will close this. Have suggested to @webpack that they adopt http://semver.org to avoid confusion.

**Comment by basarat** [comment]
I just did `npm install webpack webpack-dev-server --save-dev` in a new project and got webpack 2.0-beta with dev server at 1.x and `npm warn` of saying that dev server wants webpack < 3 and beta was out of range. Facepalm (happens to the best of us). Hopefully they will fix it soon (if possible `¯\_(ツ)_/¯.`) :rose:
